# Generated by Django 4.0.3 on 2022-03-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_upload',
            name='id',
        ),
        migrations.AddField(
            model_name='file_upload',
            name='ids',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
