# Generated by Django 4.0.3 on 2022-03-20 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0004_alter_file_upload_user_specific'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='user_specific',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
