# Generated by Django 4.0.3 on 2022-03-26 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_alter_file_upload_my_file_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
